
title: My Resume
url: 'franceswong.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2 #teal 
#style: styles-3 #green theme
#style: styles-4 #purple
#style: styles-5 #orange, no ...
#style: styles-6 #dark theme


#Profile information
name: Frances Wong
tagline: PhD Candidate
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: frances.wong@mail.utoronto.ca
website: FTW.com #do not add http://
linkedin: FrancesWong
github: FrancesWong

#Update all the sections by editing the files inside _includes folder.
